mailer:
  creds:
    props:
      mail.smtp.auth: "true"
      mail.smtp.starttls.enable: "true"
      mail.smtp.host: "outlook.office365.com"
      mail.smtp.port: "587"
    mailId: "dneldnelnelfne"
    password: "qlkdnqlfnefn"
  sender: "lnelnlnlk"
  recipients:
    - "klanklenlenflwenf"
    - "cvcefvvefvefvefvefvefvefv"

version: "km;vmef;cmef;cvm"
env: "kwklcwkcn"

